r_arm_controller:
  type: "r2_controllers_gazebo/R2JointTrajectoryActionController"
  joints:
    - /r2/right_arm/joint0
    - /r2/right_arm/joint1
    - /r2/right_arm/joint2
    - /r2/right_arm/joint3
    - /r2/right_arm/joint4
    - /r2/right_arm/joint5
    - /r2/right_arm/joint6
  gains:
    r2/right_arm/joint0: {p: 200.0, d: 0, i: 0, i_clamp: 4.0}
    r2/right_arm/joint1: {p: 200.0, d: 0, i: 0, i_clamp: 4.0}
    r2/right_arm/joint2: {p: 200.0, d: 0, i: 0, i_clamp: 4.0}
    r2/right_arm/joint3: {p: 200.0, d: 0, i: 0, i_clamp: 4.0}
    r2/right_arm/joint4: {p: 200.0, d: 0, i: 0, i_clamp: 2.0}
    r2/right_arm/joint5: {p: 200.0, d: 0, i: 0, i_clamp: 2.0}
    r2/right_arm/joint6: {p: 200.0, d: 0, i: 0, i_clamp: 2.0}
  joint_trajectory_action_node:
    joints:
      - /r2/right_arm/joint0
      - /r2/right_arm/joint1
      - /r2/right_arm/joint2
      - /r2/right_arm/joint3
      - /r2/right_arm/joint4
      - /r2/right_arm/joint5
      - /r2/right_arm/joint6
    constraints:
      goal_time: 1.0
      r2/right_arm/joint0:
        goal: 0.2
      r2/right_arm/joint1:
        goal: 0.2
      r2/right_arm/joint2:
        goal: 0.2
      r2/right_arm/joint3:
        goal: 0.2
      r2/right_arm/joint4:
        goal: 0.2
      r2/right_arm/joint5:
        goal: 0.2
      r2/right_arm/joint6:
        goal: 0.2

l_arm_controller:
  type: "r2_controllers_gazebo/R2JointTrajectoryActionController"
  joints:
    - /r2/left_arm/joint0
    - /r2/left_arm/joint1
    - /r2/left_arm/joint2
    - /r2/left_arm/joint3
    - /r2/left_arm/joint4
    - /r2/left_arm/joint5
    - /r2/left_arm/joint6
  gains:
    r2/left_arm/joint0: {p: 200.0, d: 0, i: 0.0, i_clamp: 4.0}
    r2/left_arm/joint1: {p: 200.0, d: 0, i: 0.0, i_clamp: 4.0}
    r2/left_arm/joint2: {p: 200.0, d: 0, i: 0.0, i_clamp: 4.0}
    r2/left_arm/joint3: {p: 200.0, d: 0, i: 0, i_clamp: 4.0}
    r2/left_arm/joint4: {p: 200.0, d: 0, i: 0, i_clamp: 2.0}
    r2/left_arm/joint5: {p: 200.0, d: 0, i: 0, i_clamp: 2.0}
    r2/left_arm/joint6: {p: 200.0, d: 0, i: 0, i_clamp: 2.0}
  joint_trajectory_action_node:
    joints:
      - /r2/left_arm/joint0
      - /r2/left_arm/joint1
      - /r2/left_arm/joint2
      - /r2/left_arm/joint3
      - /r2/left_arm/joint4
      - /r2/left_arm/joint5
      - /r2/left_arm/joint6
    constraints:
      goal_time: 1.0
      r2/left_arm/joint0:
        goal: 0.2
      r2/left_arm/joint1:
        goal: 0.2
      r2/left_arm/joint2:
        goal: 0.2
      r2/left_arm/joint3:
        goal: 0.2
      r2/left_arm/joint4:
        goal: 0.2
      r2/left_arm/joint5:
        goal: 0.2
      r2/left_arm/joint6:
        goal: 0.2
  
