/* Auto-generated by genmsg_cpp for file /home/ubuntu/work/robonaut2_taskboard_controller/stacks/nasa_r2_simulator/gazebo_taskboard/srv/ManipulatePowerCover.srv */
#ifndef GAZEBO_TASKBOARD_SERVICE_MANIPULATEPOWERCOVER_H
#define GAZEBO_TASKBOARD_SERVICE_MANIPULATEPOWERCOVER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace gazebo_taskboard
{
template <class ContainerAllocator>
struct ManipulatePowerCoverRequest_ {
  typedef ManipulatePowerCoverRequest_<ContainerAllocator> Type;

  ManipulatePowerCoverRequest_()
  : angle(0.0)
  , duration(0.0)
  {
  }

  ManipulatePowerCoverRequest_(const ContainerAllocator& _alloc)
  : angle(0.0)
  , duration(0.0)
  {
  }

  typedef double _angle_type;
  double angle;

  typedef double _duration_type;
  double duration;


  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ManipulatePowerCoverRequest
typedef  ::gazebo_taskboard::ManipulatePowerCoverRequest_<std::allocator<void> > ManipulatePowerCoverRequest;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverRequest> ManipulatePowerCoverRequestPtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverRequest const> ManipulatePowerCoverRequestConstPtr;


template <class ContainerAllocator>
struct ManipulatePowerCoverResponse_ {
  typedef ManipulatePowerCoverResponse_<ContainerAllocator> Type;

  ManipulatePowerCoverResponse_()
  : ok(false)
  {
  }

  ManipulatePowerCoverResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;


  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ManipulatePowerCoverResponse
typedef  ::gazebo_taskboard::ManipulatePowerCoverResponse_<std::allocator<void> > ManipulatePowerCoverResponse;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverResponse> ManipulatePowerCoverResponsePtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerCoverResponse const> ManipulatePowerCoverResponseConstPtr;

struct ManipulatePowerCover
{

typedef ManipulatePowerCoverRequest Request;
typedef ManipulatePowerCoverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ManipulatePowerCover
} // namespace gazebo_taskboard

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bec7600c9fce5aa19d66565f6ce396c6";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbec7600c9fce5aa1ULL;
  static const uint64_t static_value2 = 0x9d66565f6ce396c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulatePowerCoverRequest";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 angle\n\
float64 duration\n\
\n\
";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulatePowerCoverResponse";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
\n\
\n\
";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.angle);
    stream.next(m.duration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ManipulatePowerCoverRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ManipulatePowerCoverResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<gazebo_taskboard::ManipulatePowerCover> {
  static const char* value() 
  {
    return "f5cdf7033f402cd788e5611f14b40b32";
  }

  static const char* value(const gazebo_taskboard::ManipulatePowerCover&) { return value(); } 
};

template<>
struct DataType<gazebo_taskboard::ManipulatePowerCover> {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulatePowerCover";
  }

  static const char* value(const gazebo_taskboard::ManipulatePowerCover&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f5cdf7033f402cd788e5611f14b40b32";
  }

  static const char* value(const gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulatePowerCover";
  }

  static const char* value(const gazebo_taskboard::ManipulatePowerCoverRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f5cdf7033f402cd788e5611f14b40b32";
  }

  static const char* value(const gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulatePowerCover";
  }

  static const char* value(const gazebo_taskboard::ManipulatePowerCoverResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_TASKBOARD_SERVICE_MANIPULATEPOWERCOVER_H

