/* Auto-generated by genmsg_cpp for file /home/ubuntu/work/robonaut2_taskboard_controller/stacks/nasa_r2_simulator/gazebo_taskboard/srv/ManipulateNumPad.srv */
#ifndef GAZEBO_TASKBOARD_SERVICE_MANIPULATENUMPAD_H
#define GAZEBO_TASKBOARD_SERVICE_MANIPULATENUMPAD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace gazebo_taskboard
{
template <class ContainerAllocator>
struct ManipulateNumPadRequest_ {
  typedef ManipulateNumPadRequest_<ContainerAllocator> Type;

  ManipulateNumPadRequest_()
  : index(0)
  , force(0.0)
  , duration(0.0)
  {
  }

  ManipulateNumPadRequest_(const ContainerAllocator& _alloc)
  : index(0)
  , force(0.0)
  , duration(0.0)
  {
  }

  typedef int32_t _index_type;
  int32_t index;

  typedef double _force_type;
  double force;

  typedef double _duration_type;
  double duration;


  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ManipulateNumPadRequest
typedef  ::gazebo_taskboard::ManipulateNumPadRequest_<std::allocator<void> > ManipulateNumPadRequest;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest> ManipulateNumPadRequestPtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest const> ManipulateNumPadRequestConstPtr;


template <class ContainerAllocator>
struct ManipulateNumPadResponse_ {
  typedef ManipulateNumPadResponse_<ContainerAllocator> Type;

  ManipulateNumPadResponse_()
  : ok(false)
  {
  }

  ManipulateNumPadResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;


  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ManipulateNumPadResponse
typedef  ::gazebo_taskboard::ManipulateNumPadResponse_<std::allocator<void> > ManipulateNumPadResponse;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadResponse> ManipulateNumPadResponsePtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadResponse const> ManipulateNumPadResponseConstPtr;

struct ManipulateNumPad
{

typedef ManipulateNumPadRequest Request;
typedef ManipulateNumPadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ManipulateNumPad
} // namespace gazebo_taskboard

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aa2174eb90f087e819a238e0495526d8";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xaa2174eb90f087e8ULL;
  static const uint64_t static_value2 = 0x19a238e0495526d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateNumPadRequest";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 index\n\
float64 force\n\
float64 duration\n\
\n\
";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateNumPadResponse";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
\n\
\n\
";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.index);
    stream.next(m.force);
    stream.next(m.duration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ManipulateNumPadRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ManipulateNumPadResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<gazebo_taskboard::ManipulateNumPad> {
  static const char* value() 
  {
    return "b8003f72ab0847f72cc48d810ab5c4e4";
  }

  static const char* value(const gazebo_taskboard::ManipulateNumPad&) { return value(); } 
};

template<>
struct DataType<gazebo_taskboard::ManipulateNumPad> {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateNumPad";
  }

  static const char* value(const gazebo_taskboard::ManipulateNumPad&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b8003f72ab0847f72cc48d810ab5c4e4";
  }

  static const char* value(const gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateNumPad";
  }

  static const char* value(const gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b8003f72ab0847f72cc48d810ab5c4e4";
  }

  static const char* value(const gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateNumPad";
  }

  static const char* value(const gazebo_taskboard::ManipulateNumPadResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_TASKBOARD_SERVICE_MANIPULATENUMPAD_H

