/* Auto-generated by genmsg_cpp for file /home/ubuntu/work/robonaut2_taskboard_controller/stacks/nasa_r2_simulator/gazebo_taskboard/srv/ManipulateRockerSwitch.srv */
#ifndef GAZEBO_TASKBOARD_SERVICE_MANIPULATEROCKERSWITCH_H
#define GAZEBO_TASKBOARD_SERVICE_MANIPULATEROCKERSWITCH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace gazebo_taskboard
{
template <class ContainerAllocator>
struct ManipulateRockerSwitchRequest_ {
  typedef ManipulateRockerSwitchRequest_<ContainerAllocator> Type;

  ManipulateRockerSwitchRequest_()
  : torque(0.0)
  , duration(0.0)
  {
  }

  ManipulateRockerSwitchRequest_(const ContainerAllocator& _alloc)
  : torque(0.0)
  , duration(0.0)
  {
  }

  typedef double _torque_type;
  double torque;

  typedef double _duration_type;
  double duration;


  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ManipulateRockerSwitchRequest
typedef  ::gazebo_taskboard::ManipulateRockerSwitchRequest_<std::allocator<void> > ManipulateRockerSwitchRequest;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchRequest> ManipulateRockerSwitchRequestPtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchRequest const> ManipulateRockerSwitchRequestConstPtr;


template <class ContainerAllocator>
struct ManipulateRockerSwitchResponse_ {
  typedef ManipulateRockerSwitchResponse_<ContainerAllocator> Type;

  ManipulateRockerSwitchResponse_()
  : ok(false)
  {
  }

  ManipulateRockerSwitchResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;


  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ManipulateRockerSwitchResponse
typedef  ::gazebo_taskboard::ManipulateRockerSwitchResponse_<std::allocator<void> > ManipulateRockerSwitchResponse;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchResponse> ManipulateRockerSwitchResponsePtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateRockerSwitchResponse const> ManipulateRockerSwitchResponseConstPtr;

struct ManipulateRockerSwitch
{

typedef ManipulateRockerSwitchRequest Request;
typedef ManipulateRockerSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ManipulateRockerSwitch
} // namespace gazebo_taskboard

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1050942bb5e56893a9ebd0315acc6861";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1050942bb5e56893ULL;
  static const uint64_t static_value2 = 0xa9ebd0315acc6861ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateRockerSwitchRequest";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 torque\n\
float64 duration\n\
\n\
";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateRockerSwitchResponse";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
\n\
\n\
";
  }

  static const char* value(const  ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.torque);
    stream.next(m.duration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ManipulateRockerSwitchRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ManipulateRockerSwitchResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<gazebo_taskboard::ManipulateRockerSwitch> {
  static const char* value() 
  {
    return "9edd0381c5449d6b11bbee9496c6718d";
  }

  static const char* value(const gazebo_taskboard::ManipulateRockerSwitch&) { return value(); } 
};

template<>
struct DataType<gazebo_taskboard::ManipulateRockerSwitch> {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateRockerSwitch";
  }

  static const char* value(const gazebo_taskboard::ManipulateRockerSwitch&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9edd0381c5449d6b11bbee9496c6718d";
  }

  static const char* value(const gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateRockerSwitch";
  }

  static const char* value(const gazebo_taskboard::ManipulateRockerSwitchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9edd0381c5449d6b11bbee9496c6718d";
  }

  static const char* value(const gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gazebo_taskboard/ManipulateRockerSwitch";
  }

  static const char* value(const gazebo_taskboard::ManipulateRockerSwitchResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_TASKBOARD_SERVICE_MANIPULATEROCKERSWITCH_H

